# Generated by Django 3.1.7 on 2021-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('home_name', models.CharField(max_length=100)),
                ('home_score', models.IntegerField()),
                ('away_name', models.IntegerField()),
                ('tournament', models.CharField(max_length=100)),
            ],
        ),
    ]
